### PR TITLE
eclipse-set-bot bypass pull request

### PR DESCRIPTION
**Pull request by TruongQuangSB**
By [PR#2](https://github.com/eclipse-set/.eclipsefdn/pull/2) I had set _restricts_pushes_ to "@eclipse-set-bot", because I think with this parameter, the bot can direct push to Branch without a pull request. But probably this isn't correct. This parameter allows only users in _push_restrictions_ on branch push, which I do not want.

I think the right is _bypass_pull_request_allowances_.

### CODE REVIEW

**Comment by netomi** [comment]
As you describe it, that is the correct way to setup a branch protection rule when you want to allow a specific user to bypass the need for creating a pull request. However, I am not sure if the eclipse-set-bot needs to be in the bypass list as he is the owner of the org and can anyway bypass everything unless is_admin_enforced is set to true (see https://otterdog.readthedocs.io/en/latest/reference/organization/repository/branch-protection-rule/)

**Review by netomi — APPROVED** [review]

**Comment by TruongQuangSB** [comment]
> As you describe it, that is the correct way to setup a branch protection rule when you want to allow a specific user to bypass the need for creating a pull request. However, I am not sure if the eclipse-set-bot needs to be in the bypass list as he is the owner of the org and can anyway bypass everything unless is_admin_enforced is set to true (see https://otterdog.readthedocs.io/en/latest/reference/organization/repository/branch-protection-rule/)

ok, then this is unnecessary to set bypass for the bot

**Comment by netomi** [comment]
change has been applied.

**Comment by netomi** [comment]
btw. you can review the current configuration also on the generated site for this repo:

https://eclipse-set.github.io/.eclipsefdn/

There you will see all resources and their full configuration.

**Comment by TruongQuangSB** [comment]
ok, thanks

**Pull request merged**
